### ISSUE TITLE
Unexpected Crash Occured

### ISSUE THREAD

**Issue by litkzh** [frzyc/genshin-optimizer#1016]
_Not sure how to reproduce, as it seems like the error persists despite different browsers (Google Chrome with extensions, without extensions [guest/incognito], Safari)._

_Problem persists when all GO data has been cleared._

_DM me on Discord if you need anything:  **Lit#1924**_

```
Message: Loading chunk 592 failed.
(error: https://frzyc.github.io/3d2d41d08b6755e0d477851724303711900c123fcbb5728cc6447872acf35789/common.ed892f2298d1586a.js)
Name: ChunkLoadError
Stack: ChunkLoadError: Loading chunk 592 failed.
(error: https://frzyc.github.io/3d2d41d08b6755e0d477851724303711900c123fcbb5728cc6447872acf35789/common.ed892f2298d1586a.js)
    at i.f.j (https://frzyc.github.io/genshin-optimizer/runtime.e433ce85debbe847.js:1:3497)
    at https://frzyc.github.io/genshin-optimizer/runtime.e433ce85debbe847.js:1:1216
    at Array.reduce (<anonymous>)
    at i.e (https://frzyc.github.io/genshin-optimizer/runtime.e433ce85debbe847.js:1:1194)
    at https://frzyc.github.io/genshin-optimizer/main.7edb15a5801f0e26.js:125:1307916
    at G (https://frzyc.github.io/genshin-optimizer/main.7edb15a5801f0e26.js:125:7562243)
    at ws (https://frzyc.github.io/genshin-optimizer/main.7edb15a5801f0e26.js:125:7520662)
    at Bl (https://frzyc.github.io/genshin-optimizer/main.7edb15a5801f0e26.js:125:7509172)
    at Ql (https://frzyc.github.io/genshin-optimizer/main.7edb15a5801f0e26.js:125:7509100)
    at Cl (https://frzyc.github.io/genshin-optimizer/main.7edb15a5801f0e26.js:125:7508963)
```

**Comment by nguyentvan7** [comment]
Are you still encountering this issue? I think its a github issue so not sure how much we can do

**Comment by litkzh** [comment]
yeah, but if it's a github issue then yeah not much that can be done there, thanks
