### ISSUE TITLE
TC solver crash

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#2334]
Optimizer will crash if there is no value in the inputs highlighted in the screenshot below with the following error.
```
Message: Invalid array length
Name: RangeError
Stack: RangeError: Invalid array length
    at aEe (https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:131:53914)
    at https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:262:10545
    at nb (https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:46:17033)
    at Vx (https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:48:1575)
    at MV (https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:48:46080)
    at SV (https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:48:39822)
    at Afe (https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:48:39748)
    at BR (https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:48:39598)
    at Hv (https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:48:35960)
    at vV (https://frzyc.github.io/genshin-optimizer/assets/index-DRU-rULh.js:48:34907)
```

![image](https://github.com/user-attachments/assets/c6e1e5bd-2557-4f76-98b8-0c9171c6effa)

https://discord.com/channels/785153694478893126/1264329532773498891

**Comment by Kirk-KD** [comment]
Cannot replicate, according to the log it's skipping the build, which I think is supposed to happen right?

![image](https://github.com/user-attachments/assets/b421b9b9-19a3-49f2-8c3a-9b2e2db3a254)

![image](https://github.com/user-attachments/assets/eb3863f9-1f8c-402e-84a7-2c0b7d83fc19)

**Comment by nguyentvan7** [comment]
Also can't replicate
