### ISSUE TITLE
Cloud (Google Drive) sync

### ISSUE THREAD

**Issue by hyoretsu** [frzyc/genshin-optimizer#929]
This is as duplicate of #79 to raise awareness. It's the third time in the last 2 (possibly 1) months that my data gets randomly wiped. If I hadn't made a (outdated) backup, I'd lose 45 Characters, 255 Artifacts and 120 Weapons. This should be a priority to implement, before UI reworks and whatnot.

**Comment by nguyentvan7** [comment]
Closing as duplicate.

Sounds like you might have some kind of "cleaning" program on your PC like CCleaner or something that wipes your cookies, which might be worth looking into.

You are free to back up your DB more often, I do mine every time I scan my artifacts.

We can determine our own priority, thanks. You're free to raise your own PR if it is an extra priority for you

**Comment by hyoretsu** [comment]
I have no such software on my PC and that's only an issue in Genshin Optimizer. I don't get logged out from other sites, like Cookie Clicker which also stores saves locally.

**Comment by nguyentvan7** [comment]
Well unfortunately we are just doing this with our own motivation, and are not the same devs as Paimon.Moe and so don't have the same skillset. I'm sure it could be straightforward, but none of the dev team has done it before and have not had the time to devote to it yet.

Seems you are implying it is easy, so I look forward to the PR from your end, thanks :)

**Comment by hyoretsu** [comment]
With one of the repos needed to even run the application not existing/being private, sure.

```
> nx run dm:loadDM

/home/hyoretsu/@Projects/genshin-optimizer/libs/dm/GenshinData doesn't exist, cloning repo...
Cloning into 'GenshinData'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Command failed: git clone git@github.com:Dimbreath/GenshinData.git --depth 1
Cloning into 'GenshinData'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (/home/hyoretsu/@Projects/genshin-optimizer/libs/dm/scripts/loadDM.ts:13:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/home/hyoretsu/@Projects/genshin-optimizer/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/home/hyoretsu/@Projects/genshin-optimizer/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(185) [Uint8Array] [
       67, 108, 111, 110, 105, 110, 103,  32, 105, 110, 116, 111,
       32,  39,  71, 101, 110, 115, 104, 105, 110,  68,  97, 116,
       97,  39,  46,  46,  46,  10,  69,  82,  82,  79,  82,  58,
       32,  82, 101, 112, 111, 115, 105, 116, 111, 114, 121,  32,
      110, 111, 116,  32, 102, 111, 117, 110, 100,  46,  10, 102,
       97, 116,  97, 108,  58,  32,  67, 111, 117, 108, 100,  32,
      110, 111, 116,  32, 114, 101,  97, 100,  32, 102, 114, 111,
      109,  32, 114, 101, 109, 111, 116, 101,  32, 114, 101, 112,
      111, 115, 105, 116,
      ... 85 more items
    ]
  ],
  pid: 42652,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(185) [Uint8Array] [
     67, 108, 111, 110, 105, 110, 103,  32, 105, 110, 116, 111,
     32,  39,  71, 101, 110, 115, 104, 105, 110,  68,  97, 116,
     97,  39,  46,  46,  46,  10,  69,  82,  82,  79,  82,  58,
     32,  82, 101, 112, 111, 115, 105, 116, 111, 114, 121,  32,
    110, 111, 116,  32, 102, 111, 117, 110, 100,  46,  10, 102,
     97, 116,  97, 108,  58,  32,  67, 111, 117, 108, 100,  32,
    110, 111, 116,  32, 114, 101,  97, 100,  32, 102, 114, 111,
    109,  32, 114, 101, 109, 111, 116, 101,  32, 114, 101, 112,
    111, 115, 105, 116,
    ... 85 more items
  ]
}```

**Comment by nguyentvan7** [comment]
Not our fault, but I'll swap us over to the gitlab version

**Comment by nguyentvan7** [comment]
If you're itching to do it, can just copy the changes from #930 locally
